# Generated by Django 2.2.13 on 2020-06-10 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trazabilidad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('codigo', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'categoría de alimento',
                'verbose_name_plural': 'categorías de alimentos',
            },
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('codigo', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200, verbose_name='descripción')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='alimentos.Categoria')),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentos_subcategoria_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'subcategoría de alimento',
                'verbose_name_plural': 'subcategorías de alimentos',
            },
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentos_solicitante_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'solicitante',
                'verbose_name_plural': 'solicitantes',
            },
        ),
        migrations.CreateModel(
            name='InformacionAlimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=100, verbose_name='dirección')),
                ('responsable', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=100)),
                ('sitio_toma', models.CharField(max_length=100, verbose_name='sitio de la toma')),
                ('direccion_recoleccion', models.CharField(max_length=100, verbose_name='dirección')),
                ('fecha', models.DateTimeField()),
                ('poblado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trazabilidad.Poblado')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alimentos.Solicitante')),
            ],
            options={
                'verbose_name': 'información general de las muestras de alimento',
                'verbose_name_plural': 'información general de las muestras de alimento',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('codigo', models.IntegerField()),
                ('descripcion', models.CharField(max_length=250, verbose_name='descripción')),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentos_grupo_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'grupo de alimento',
                'verbose_name_plural': 'grupos de alimentos',
            },
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentos_fabricante_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'fabricante',
                'verbose_name_plural': 'fabricantes',
            },
        ),
        migrations.CreateModel(
            name='Distribuidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentos_distribuidor_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'distribuidor',
                'verbose_name_plural': 'distribuidores',
            },
        ),
        migrations.CreateModel(
            name='Decreto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trazabilidad.Area')),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentos_decreto_set', to=settings.AUTH_USER_MODEL)),
                ('pruebas', models.ManyToManyField(related_name='pruebas_alimentos', to='trazabilidad.Prueba')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alimentos.Categoria')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='categoria',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='alimentos.Grupo'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='modificado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentos_categoria_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('muestra_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trazabilidad.Muestra')),
                ('unidad_muestra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='n. unidad de muestra')),
                ('contenido_neto', models.CharField(blank=True, max_length=100, verbose_name='contenido neto por unidad de muestra')),
                ('unidad_contramuestra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='n. unidad de contramuestra')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='descripción del producto según el rótulo')),
                ('registro_sanitario', models.CharField(blank=True, max_length=200)),
                ('lote', models.CharField(blank=True, max_length=200)),
                ('ano_vencimiento', models.PositiveIntegerField(blank=True, null=True)),
                ('mes_vencimiento', models.PositiveIntegerField(blank=True, null=True)),
                ('dia_vencimiento', models.PositiveIntegerField(blank=True, null=True)),
                ('propietario', models.CharField(blank=True, max_length=200)),
                ('importador', models.CharField(blank=True, max_length=100)),
                ('direccion_importador', models.CharField(blank=True, max_length=130)),
                ('responsable_entrega', models.CharField(blank=True, max_length=100, verbose_name='responsable de la entrega')),
                ('temperatura', models.CharField(blank=True, max_length=100)),
                ('temperatura_recoleccion', models.CharField(blank=True, max_length=100)),
                ('cumple', models.NullBooleanField(choices=[(True, 'Si'), (False, 'No'), (None, 'No Aplica')], verbose_name='cumple con criterios de aceptación')),
                ('cadena_custodia', models.NullBooleanField(choices=[(True, 'Si'), (False, 'No'), (None, 'No Aplica')], verbose_name='cadena de custodia')),
                ('constancia_pago', models.NullBooleanField(choices=[(True, 'Si'), (False, 'No'), (None, 'No Aplica')], verbose_name='constancia de pago')),
                ('decretos', models.ManyToManyField(blank=True, related_name='muestras_alimento', to='alimentos.Decreto')),
                ('distribuidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alimentos.Distribuidor')),
                ('fabricante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alimentos.Fabricante')),
                ('informacion_general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alimentos.InformacionAlimento')),
                ('motivo_analisis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trazabilidad.MotivoAnalisis', verbose_name='motivo del analisis')),
                ('subcategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alimentos.Subcategoria', verbose_name='sub-categoria')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alimentos.Categoria', verbose_name='tipo de alimento')),
            ],
            options={
                'verbose_name': 'muestra de alimento',
                'verbose_name_plural': 'muestras de alimento',
            },
            bases=('trazabilidad.muestra',),
        ),
    ]
