# Generated by Django 2.2.13 on 2020-07-03 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_auto_20200609_1944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'permissions': [('can_ingresar_muestras_covid', 'Puede ingresar muestras de covid19')], 'verbose_name': 'empleado', 'verbose_name_plural': 'empleados'},
        ),
    ]
