# Generated by Django 2.2.13 on 2020-07-07 03:03

from django.db import migrations

def set_areas(apps, schema_editor):
    Empleado = apps.get_model('administracion', 'Empleado')
    for empleado in Empleado.objects.all():
        empleado.areas.add(empleado.area)

class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_auto_20200706_2201'),
    ]

    operations = [
        migrations.RunPython(set_areas, reverse_code=migrations.RunPython.noop),
    ]
