# Generated by Django 2.2.13 on 2020-07-14 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0007_auto_20200714_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'permissions': [('can_see_analisis', 'Puede ver pagina de analisis'), ('can_see_ingresos_recepcionados', 'Puede ver pagina de ingresos recepcionados'), ('can_analizar_todos_programas', 'Puede ingresar analisis de todos los programas'), ('can_ingresar_muestras_programas_clinicos', 'Puede ingresar muestras de programas clinicos'), ('can_ingresar_muestras_programas_ambientes', 'Puede ingresar muestras de programas de ambientes')], 'verbose_name': 'empleado', 'verbose_name_plural': 'empleados'},
        ),
    ]
