# Generated by Django 2.2.13 on 2020-07-30 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0010_auto_20200729_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_automatica_reporte', models.BooleanField(default=False, verbose_name='Firma de reporte automatica')),
            ],
        ),
    ]
