# Generated by Django 2.2.13 on 2020-06-10 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trazabilidad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bebidas_alcoholicas_grupo_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'grupo',
                'verbose_name_plural': 'grupos',
            },
        ),
        migrations.CreateModel(
            name='TipoEnvase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bebidas_alcoholicas_tipoenvase_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tipo de envase',
                'verbose_name_plural': 'tipos de envase',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='bebidas_alcoholicas.Grupo')),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bebidas_alcoholicas_producto_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
            },
        ),
        migrations.CreateModel(
            name='MotivoAnalisis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('motivo', models.CharField(max_length=200, verbose_name='nombre del motivo')),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bebidas_alcoholicas_motivoanalisis_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'motivo de analisis',
                'verbose_name_plural': 'motivos de analisis',
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre remitente')),
                ('direccion', models.CharField(blank=True, max_length=100, verbose_name='dirección remitente')),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bebidas_alcoholicas_institucion_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'institución',
                'verbose_name_plural': 'instituciones',
            },
        ),
        migrations.CreateModel(
            name='InformacionBebidaAlcoholica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable_entrega', models.CharField(max_length=200, verbose_name='nombre responsable de entrega')),
                ('cargo', models.CharField(max_length=100)),
                ('numero_caso', models.CharField(max_length=100, verbose_name='n. de caso')),
                ('numero_oficio', models.CharField(max_length=100, verbose_name='n. de oficio')),
                ('sitio_toma', models.CharField(blank=True, max_length=100, verbose_name='sitio de la toma')),
                ('propietario', models.CharField(blank=True, max_length=100, verbose_name='propietario del producto')),
                ('direccion', models.CharField(blank=True, max_length=100, verbose_name='dirección')),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bebidas_alcoholicas.Institucion', verbose_name='institución')),
                ('poblado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trazabilidad.Poblado')),
            ],
            options={
                'verbose_name': 'información general de las muestras de bebidas alcoholicas',
                'verbose_name_plural': 'información general de las muestras de bebidas alcoholicas',
            },
        ),
        migrations.CreateModel(
            name='Decreto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decretos', to='bebidas_alcoholicas.Grupo')),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bebidas_alcoholicas_decreto_set', to=settings.AUTH_USER_MODEL)),
                ('pruebas', models.ManyToManyField(to='trazabilidad.Prueba')),
            ],
            options={
                'verbose_name': 'decreto',
                'verbose_name_plural': 'decretos',
            },
        ),
        migrations.CreateModel(
            name='BebidaAlcoholica',
            fields=[
                ('muestra_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trazabilidad.Muestra')),
                ('temperatura', models.CharField(blank=True, max_length=100, verbose_name='temperatura de ingreso')),
                ('registro_sanitario', models.CharField(blank=True, max_length=150, verbose_name='registro sanitario')),
                ('numero_lote', models.CharField(blank=True, max_length=100, verbose_name='n. lote')),
                ('ano_vencimiento', models.PositiveIntegerField(blank=True, null=True)),
                ('mes_vencimiento', models.PositiveIntegerField(blank=True, null=True)),
                ('dia_vencimiento', models.PositiveIntegerField(blank=True, null=True)),
                ('no_aplica_vencimiento', models.NullBooleanField()),
                ('fabricante', models.CharField(blank=True, max_length=150, verbose_name='empresa fabricante')),
                ('direccion_fabricante', models.CharField(blank=True, max_length=100, verbose_name='dirección fabricante')),
                ('grado', models.CharField(blank=True, max_length=100, verbose_name='grado alcoholimetrico declarado')),
                ('contenido', models.CharField(blank=True, max_length=200, verbose_name='contenido declarado')),
                ('aspecto_externo', models.NullBooleanField(choices=[(True, 'BUENO'), (False, 'MALO')])),
                ('aspecto_interno', models.NullBooleanField(choices=[(True, 'BUENO'), (False, 'MALO')])),
                ('hermeticidad', models.NullBooleanField(choices=[(True, 'BUENO'), (False, 'MALO')])),
                ('decreto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bebidas_alcoholicas.Decreto', verbose_name='decreto')),
                ('informacion_general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bebidas_alcoholicas.InformacionBebidaAlcoholica')),
                ('motivo_analisis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bebidas_alcoholicas.MotivoAnalisis', verbose_name='motivo del analisis')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bebidas_alcoholicas.Producto', verbose_name='nombre comercial del producto')),
                ('tipo_envase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bebidas_alcoholicas.TipoEnvase', verbose_name='tipo de envase')),
            ],
            options={
                'verbose_name': 'muestra de bebida alcoholica',
                'verbose_name_plural': 'muestras de bebidas alcoholicas',
            },
            bases=('trazabilidad.muestra',),
        ),
    ]
