# Generated by Django 2.2.13 on 2020-07-03 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='eps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='trazabilidad.Eps', verbose_name='eps-plan'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tipo_edad',
            field=models.CharField(blank=True, choices=[('A', 'Años'), ('M', 'Meses'), ('D', 'Dias'), ('H', 'Horas')], max_length=1),
        ),
    ]
