# Generated by Django 2.2.13 on 2020-07-07 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0003_recepcion_responsable_tecnico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporte',
            options={'permissions': [('can_generar_informe', 'Puede generar nuevo informe de resultado'), ('can_see_informe_resultados', 'Puede ver informe de resultado regenerado')], 'verbose_name': 'reporte', 'verbose_name_plural': 'reportes'},
        ),
    ]
