# Generated by Django 2.2.13 on 2020-07-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0004_auto_20200707_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestra',
            name='temp_ingreso',
            field=models.FloatField(blank=True, null=True, verbose_name='temperatura de ingreso'),
        ),
        migrations.AddField(
            model_name='muestra',
            name='temp_procesamiento',
            field=models.FloatField(blank=True, null=True, verbose_name='temperatura de procesamiento'),
        ),
    ]
