# Generated by Django 2.2.13 on 2020-07-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0005_auto_20200713_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muestra',
            name='temp_ingreso',
            field=models.FloatField(blank=True, null=True, verbose_name='temperatura de muestra ºC'),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='temp_procesamiento',
            field=models.FloatField(blank=True, null=True, verbose_name='temperatura de procesamiento ºC'),
        ),
    ]
