# Generated by Django 2.2.13 on 2020-07-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0008_recepcion_fecha_envio_resultados'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='email',
            field=models.EmailField(default='conf@mail.com', max_length=254),
            preserve_default=False,
        ),
    ]
