# Generated by Django 2.2.13 on 2020-07-28 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0009_municipio_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de aprobación'),
        ),
    ]
