# Generated by Django 2.2.14 on 2020-08-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0011_update_fecha_aprobacion_reporte_20200729_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, verbose_name='apellidos'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, verbose_name='nombres'),
        ),
    ]
