# Generated by Django 2.2.13 on 2020-06-10 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
        ('trazabilidad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trazabilidad.Area'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='modificado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_equipo_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
