# Generated by Django 2.2.13 on 2020-07-03 17:36

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trazabilidad', '0002_auto_20200703_1236'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cie10_django', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eapb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covid19_eapb_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InfoGeneral346',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(blank=True, choices=[('346', 'COVID-19'), ('345', 'ESI/IRAG'), ('348', 'IRAG INSITADO')], max_length=4)),
                ('fecha_notificacion', models.DateField(blank=True, null=True, verbose_name='fecha de la notificación')),
                ('fuente', models.CharField(blank=True, choices=[('5', 'Investigaciones'), ('2', 'Busqueda activa ins.'), ('4', 'Busqueda activa com.'), ('3', 'Vigilancia intensificada'), ('1', 'Notificacion rutinaria')], max_length=2, null=True)),
                ('pais_residencia', django_countries.fields.CountryField(default='CO', max_length=2, verbose_name='pais de residencia')),
                ('direccion', models.CharField(blank=True, max_length=150, verbose_name='dirección de residencia')),
                ('fecha_consulta', models.DateField(blank=True, null=True, verbose_name='fecha de consulta')),
                ('fecha_inicio_sintomas', models.DateField(blank=True, null=True, verbose_name='fecha de inicio de sintomas')),
                ('clasificacion_inicial_caso', models.CharField(blank=True, choices=[('2', 'Probable'), ('1', 'Sospechoso'), ('5', 'Conf. clinica'), ('4', 'Conf. por laboratorio'), ('3', 'Conf. nexo epidemiologico')], max_length=2, verbose_name='clasificación inicial de caso')),
                ('hospitalizado', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2)),
                ('fecha_hospitalizacion', models.DateField(blank=True, null=True, verbose_name='fecha de hospitalización')),
                ('condicion_final', models.CharField(blank=True, choices=[('1', 'Vivo'), ('2', 'Muerto'), ('0', 'No sabe, no responde')], max_length=2)),
                ('fecha_defuncion', models.DateField(blank=True, null=True, verbose_name='fecha de defunción')),
                ('certificado_defuncion', models.CharField(blank=True, max_length=100, verbose_name='número de certificado de defunción')),
                ('profesional_diligenciante', models.CharField(blank=True, max_length=200, verbose_name='nombre del profesional que diligencio la ficha')),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('fecha_ajuste', models.DateField(blank=True, null=True, verbose_name='fecha de ajuste')),
                ('clasificacion_final_caso', models.CharField(blank=True, choices=[('0', 'No aplica'), ('6', 'Descartado'), ('5', 'Conf. clinica'), ('7', 'Otra actualización'), ('4', 'Conf. por laboratorio'), ('3', 'Conf. nexo epidemiologico'), ('D', 'Descartado por error de digitación')], max_length=2, verbose_name='seguimiento y clasificación final de caso')),
                ('trabajador_salud', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, verbose_name='¿Es trabajador de la salud otro personal del ambito hospitalario que haya tenido contacto estrecho con un caso probable o confirmado por nuevo virus?')),
                ('viajo_area_con_virus', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, verbose_name='¿Viajo a areas de circulación del virus nuevo?')),
                ('viaje_nacional', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, verbose_name='¿El Viaje fue en territorio nacional?')),
                ('viaje_internacional', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, verbose_name='¿El Viaje fue internacional?')),
                ('pais_viaje_iternacional', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='¿donde?')),
                ('contacto_caso_confirmado', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, verbose_name='¿tuvo contacto estrecho en los últimos 14 días con un caso probable o confirmado con infección respiratoria aguda grave por virus nuevo?')),
                ('sintomas', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('TOS', 'Tos'), ('FI', 'Fiebre'), ('OD', 'Odinofagia'), ('FA', 'Fatiga o adinamia'), ('DR', 'Dificulta respiratoria')], max_length=4), blank=True, null=True, size=None)),
                ('influenza_estacional', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No'), ('DE', 'Desconocido')], max_length=2)),
                ('dosis_influenza_estacional', models.CharField(blank=True, max_length=10, verbose_name='dosis')),
                ('antecedentes_clinicos', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('VIH', 'VIH'), ('EP', 'EPOC'), ('AS', 'Asma'), ('OT', 'Otros'), ('CA', 'Cancer'), ('FU', 'Fumador'), ('OB', 'Obesidad'), ('DI', 'Diabetes'), ('DE', 'Desnutrición'), ('TU', 'Tuberculosis'), ('EC', 'Enfermedad cardiaca'), ('IR', 'Insuficiencia renal'), ('MI', 'Toma medicamentos inmusupresores')], max_length=3), blank=True, null=True, size=None)),
                ('otros_antecedentes_clinicos', models.CharField(blank=True, max_length=3, verbose_name='¿cuáles otros?')),
                ('radiografia_torax', models.CharField(blank=True, choices=[('3', 'Ninguno'), ('1', 'Infiltrado alveolar o neumonía'), ('2', 'Infiltrados intersticiales')], max_length=2)),
                ('antibiotico_ultimas_semanas', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2)),
                ('causa_muerte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cie10_django.CIE10', verbose_name='causa básica de muerte')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Upgd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('subindice', models.CharField(max_length=10)),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covid19_upgd_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tipificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covid19_tipificacion_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Muestra346',
            fields=[
                ('muestra_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trazabilidad.Muestra')),
                ('fecha_toma', models.DateField()),
                ('informacion_general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid19.InfoGeneral346')),
                ('tipo_muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muestras_346', to='trazabilidad.TipoMuestra')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('trazabilidad.muestra',),
        ),
        migrations.CreateModel(
            name='InfoPaciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='teléfono')),
                ('nacionalidad', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='nacionalidad')),
                ('pais_ocurrencia', django_countries.fields.CountryField(blank=True, default='CO', max_length=2, verbose_name='pais de ocurrencia del caso')),
                ('area_ocurrencia', models.CharField(blank=True, choices=[('RD', 'Rural disperso'), ('CP', 'centro poblado'), ('CB', 'Cabecera municipal')], max_length=3, verbose_name='área de ocurrencia del caso')),
                ('localidad_ocurrencia', models.CharField(blank=True, max_length=200, verbose_name='localidad de ocurrencia del caso')),
                ('barrio_ocurrencia', models.CharField(blank=True, max_length=200, verbose_name='barrio de ocurrencia del caso')),
                ('lugar_ocurrencia', models.CharField(blank=True, max_length=200, verbose_name='cabecera municipal/centro poblado/rural disperso')),
                ('vereda_zona', models.CharField(blank=True, max_length=200, verbose_name='vereda/zona')),
                ('tipo_regimen', models.CharField(blank=True, choices=[('E', 'Especial'), ('P', 'Excepción'), ('S', 'Subsidiado'), ('N', 'No asegurado'), ('C', 'Contributivo'), ('I', 'Indeterminado/Pendiente')], max_length=1, verbose_name='tipo de régimen en salud')),
                ('pertenencia_etnica', models.CharField(blank=True, choices=[('O', 'Otro'), ('R', 'Raizal'), ('I', 'Indígena'), ('G', 'Rom, Gitano'), ('P', 'Palenquero'), ('N', 'Negro, mulato afro colombiano')], max_length=1)),
                ('grupo_etnico', models.CharField(blank=True, max_length=200)),
                ('estrato', models.CharField(blank=True, choices=[('1', 'Bajo-Bajo'), ('2', 'Bajo'), ('3', 'Medio-Bajo'), ('4', 'Medio'), ('5', 'Medio-Alto'), ('6', 'Alto')], max_length=1)),
                ('grupos_poblacionales', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('MI', 'Migrantes'), ('GE', 'Gestantes'), ('IN', 'Indigentes'), ('CA', 'Carcelarios'), ('DE', 'Desplazados'), ('DI', 'Discapacitados'), ('DES', 'Desmovilizados'), ('O', 'Otros grupos poblacionales'), ('MC', 'Madres comunitarias'), ('CP', 'Centros psiquiátricos'), ('PI', 'Poblacion infantil a cargo del ICBF'), ('VVA', 'Victimas de violencia armada')], max_length=4), blank=True, null=True, size=None)),
                ('semanas_gestacion', models.CharField(blank=True, max_length=100, verbose_name='sem. de gestación')),
                ('eapb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='covid19.Eapb', verbose_name='nombre de la administradora de Planes de beneficios')),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covid19_infopaciente_set', to=settings.AUTH_USER_MODEL)),
                ('municipio_ocurrencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='trazabilidad.Municipio', verbose_name='municipio de procedencia/ocurrencia')),
                ('ocupacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='covid19.Ocupacion')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info_covid19', to='trazabilidad.Paciente')),
                ('tipificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='covid19.Tipificacion', verbose_name='tipificación paciente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='infogeneral346',
            name='info_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_muestras_346', to='covid19.InfoPaciente'),
        ),
        migrations.AddField(
            model_name='infogeneral346',
            name='municipio_residencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='trazabilidad.Municipio', verbose_name='municipio de residencia'),
        ),
        migrations.AddField(
            model_name='infogeneral346',
            name='municipio_upgd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='trazabilidad.Municipio'),
        ),
        migrations.AddField(
            model_name='infogeneral346',
            name='municipio_viaje_nacional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='trazabilidad.Municipio', verbose_name='¿Donde?'),
        ),
        migrations.AddField(
            model_name='infogeneral346',
            name='upgd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='covid19.Upgd'),
        ),
    ]
