# Generated by Django 2.2.13 on 2020-07-14 15:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0003_auto_20200709_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infogeneral346',
            name='antecedentes_clinicos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('AS', 'Asma'), ('OB', 'Obesidad'), ('EP', 'EPOC'), ('IR', 'Insuficiencia renal'), ('DI', 'Diabetes'), ('MI', 'Toma medicamentos inmusupresores'), ('VIH', 'VIH'), ('FU', 'Fumador'), ('EC', 'Enfermedad cardiaca'), ('TU', 'Tuberculosis'), ('CA', 'Cancer'), ('DE', 'Desnutrición'), ('OT', 'Otros')], max_length=3), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='infogeneral346',
            name='sintomas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('TOS', 'Tos'), ('FI', 'Fiebre'), ('OD', 'Odinofagia'), ('DR', 'Dificulta respiratoria'), ('FA', 'Fatiga o adinamia')], max_length=4), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='infogeneral348',
            name='antecedentes_clinicos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('AS', 'Asma'), ('OB', 'Obesidad'), ('EP', 'EPOC'), ('IR', 'Insuficiencia renal'), ('DI', 'Diabetes'), ('MI', 'Toma medicamentos inmusupresores'), ('VIH', 'VIH'), ('FU', 'Fumador'), ('EC', 'Enfermedad cardiaca'), ('TU', 'Tuberculosis'), ('CA', 'Cancer'), ('DE', 'Desnutrición'), ('OT', 'Otros')], max_length=3), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='infopaciente',
            name='grupos_poblacionales',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('DI', 'Discapacitados'), ('DE', 'Desplazados'), ('MI', 'Migrantes'), ('CA', 'Carcelarios'), ('GE', 'Gestantes'), ('IN', 'Indigentes'), ('PI', 'Poblacion infantil a cargo del ICBF'), ('MC', 'Madres comunitarias'), ('DES', 'Desmovilizados'), ('CP', 'Centros psiquiátricos'), ('VVA', 'Victimas de violencia armada'), ('O', 'Otros grupos poblacionales')], max_length=4), blank=True, null=True, size=None),
        ),
    ]
