# Generated by Django 2.2.13 on 2020-07-14 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0004_auto_20200714_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infopaciente',
            name='fecha_nacimiento',
        ),
        migrations.AlterField(
            model_name='infopaciente',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos_covid19', to='trazabilidad.Paciente'),
        ),
    ]
