# Generated by Django 2.2.13 on 2020-07-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0006_auto_20200715_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='eapb',
            name='email',
            field=models.EmailField(default='conf@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upgd',
            name='email',
            field=models.EmailField(default='conf@mail.com', max_length=254),
            preserve_default=False,
        ),
    ]
