# Generated by Django 2.2.13 on 2020-07-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0009_auto_20200728_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgd',
            name='nombre',
            field=models.CharField(max_length=400),
        ),
    ]
