# Generated by Django 2.2.14 on 2020-08-29 00:23

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0010_auto_20200728_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infogeneral346',
            name='municipio_residencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='trazabilidad.Municipio', verbose_name='municipio de residencia'),
        ),
        migrations.AlterField(
            model_name='infogeneral346',
            name='municipio_upgd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='trazabilidad.Municipio'),
        ),
        migrations.AlterField(
            model_name='infogeneral346',
            name='pais_residencia',
            field=django_countries.fields.CountryField(blank=True, default='CO', max_length=2, null=True, verbose_name='pais de residencia'),
        ),
        migrations.AlterField(
            model_name='infogeneral346',
            name='upgd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='covid19.Upgd'),
        ),
        migrations.AlterField(
            model_name='infogeneral348',
            name='municipio_residencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='trazabilidad.Municipio', verbose_name='municipio de residencia'),
        ),
        migrations.AlterField(
            model_name='infogeneral348',
            name='municipio_upgd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='trazabilidad.Municipio'),
        ),
        migrations.AlterField(
            model_name='infogeneral348',
            name='pais_residencia',
            field=django_countries.fields.CountryField(blank=True, default='CO', max_length=2, null=True, verbose_name='pais de residencia'),
        ),
        migrations.AlterField(
            model_name='infogeneral348',
            name='upgd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='covid19.Upgd'),
        ),
        migrations.AlterField(
            model_name='muestra346',
            name='fecha_toma',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='muestra346',
            name='tipo_muestra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muestras_346', to='trazabilidad.TipoMuestra'),
        ),
        migrations.AlterField(
            model_name='muestra348',
            name='fecha_toma',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='muestra348',
            name='tipo_muestra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muestras_348', to='trazabilidad.TipoMuestra'),
        ),
    ]
